name: Build and Release Executables

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install numpy separately first to avoid source import issue
          pip install numpy --force-reinstall
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Verify NumPy installation (from outside source directory)
        run: |
          cd /tmp  # Move to a different directory for importing numpy
          python -c "import numpy; print('NumPy version:', numpy.__version__)"
          python -c "import numpy; print('NumPy libraries:', numpy.get_include())"
        shell: bash

      - name: Build executable
        env: 
          PYINSTALLER_NO_PLUGIN: "1"
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            pyinstaller --hidden-import=numpy --hidden-import=numpy.core --hidden-import=numpy.random --onedir --windowed --name backend run.py --add-data "models/logo_detection.pt;models" --exclude-module tkinter
          else
            arch -x86_64 pyinstaller --hidden-import=numpy --hidden-import=numpy.core --hidden-import=numpy.random --onedir --windowed --name backend run.py --add-data "models/logo_detection.pt:models" --exclude-module tkinter
          fi
        shell: bash

      - name: Zip build output
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            powershell Compress-Archive -Path dist/backend -DestinationPath backend-windows.zip
          else
            cd dist && zip -r ../backend-mac-x86_64.zip backend
          fi
        shell: bash

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-${{ matrix.os }}
          path: |
            backend-windows.zip
            backend-mac-x86_64.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all zipped artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.run_id }}
          tag_name: release-${{ github.run_id }}
          body: "Automated release for commit `${{ github.sha }}`"
          files: release-artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}