name: Build executables

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            pyinstaller --onedir --windowed --name backend run.py `
              --add-data "models/logo_detection.pt;models" `
              --exclude-module tkinter
          else
            pyinstaller --onedir --windowed --name backend run.py \
              --add-data "models/logo_detection.pt:models" \
              --exclude-module tkinter
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-${{ matrix.os }}
          path: dist/backend