name: Build and Release Executables

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.9"

      - name: Create virtual environment
        run: |
          python -m venv venv
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            source venv/Scripts/activate
          else
            source venv/bin/activate
          fi
        shell: bash

      - name: Install dependencies in isolated environment
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            venv/Scripts/pip install --upgrade pip
            venv/Scripts/pip install numpy
            venv/Scripts/pip install -r requirements.txt
            venv/Scripts/pip install pyinstaller
          else
            venv/bin/pip install --upgrade pip
            venv/bin/pip install numpy
            venv/bin/pip install -r requirements.txt
            venv/bin/pip install pyinstaller
          fi
        shell: bash

      - name: Build executable
        env: 
          PYINSTALLER_NO_PLUGIN: "1"
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            venv/Scripts/pyinstaller --onedir --windowed --name backend run.py --add-data "models/logo_detection.pt;models" --exclude-module tkinter
          else
            arch -x86_64 venv/bin/pyinstaller --onedir --windowed --name backend run.py --add-data "models/logo_detection.pt:models" --exclude-module tkinter
          fi
        shell: bash

      - name: Zip build output
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            powershell Compress-Archive -Path dist/backend -DestinationPath backend-windows.zip
          else
            cd dist && zip -r ../backend-mac-x86_64.zip backend
          fi
        shell: bash

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-${{ matrix.os }}
          path: |
            backend-windows.zip
            backend-mac-x86_64.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all zipped artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.run_id }}
          tag_name: release-${{ github.run_id }}
          body: "Automated release for commit `${{ github.sha }}`"
          files: release-artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}